pages:
  stage: deploy
  image: mcr.microsoft.com/playwright
  script:
  - su - pwuser -c 'DEBUG=info npx feed-me-up-scotty@main'
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - main
  retry:
    max: 2
    when: always
