pages:
  stage: deploy
  image: mcr.microsoft.com/playwright:v1.52.0-noble
  script:
  - npx playwright install-deps
  - npx playwright install firefox
  - DEBUG=info npx feed-me-up-scotty@main
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - main
  retry:
    max: 2
    when: always
