[default]
timeout = 300
filters = ["Onder bod", "Verkocht", "VERKOCHT", "dreef"]
onFail = "stale"

[peekenpompe]
title = "Peek & Pompe makelaars"
url = "https://www.peekenpompe.nl/nl/woningaanbod?ignoreType[]=isBought#{%22view%22:%22grid%22,%22sort%22:%22addedDesc%22,%22address%22:%22%22,%22title%22:%22%22,%22salesRentals%22:%22sales%22,%22salesPriceMin%22:0,%22salesPriceMax%22:400000,%22devSalesPriceMin%22:0,%22devSalesPriceMax%22:9999999999,%22rentalsPriceMin%22:0,%22rentalsPriceMax%22:9999999999,%22devRentalsPriceMin%22:0,%22devRentalsPriceMax%22:9999999999,%22surfaceMin%22:0,%22surfaceMax%22:9999999999,%22unitsMin%22:0,%22unitsMax%22:9999999999,%22devSurfaceMin%22:0,%22devSurfaceMax%22:9999999999,%22plotSurfaceMin%22:0,%22plotSurfaceMax%22:9999999999,%22roomsMin%22:2,%22roomsMax%22:9999999999,%22bedroomsMin%22:0,%22bedroomsMax%22:9999999999,%22bathroomsMin%22:0,%22bathroomsMax%22:9999999999,%22city%22:[%22Utrecht%22],%22district%22:[],%22mainType%22:[],%22buildType%22:[],%22tag%22:[],%22country%22:[],%22state%22:[],%22listingsType%22:[],%22ignoreType%22:[%22isBought%22],%22categories%22:[],%22status%22:%22available%22,%22statusStrict%22:false,%22user%22:%22%22,%22branch%22:%22%22,%22archiveTime%22:15778463,%22page%22:1}"
entrySelector = ".card-object"
titleSelector = ".card-object-address"
linkSelector = ".card-object-address"

[moib]
title = "MOIB makelaars"
url = "https://moib.nl/aanbod/"
entrySelector = ".horizon"
titleSelector = "h3"
linkSelector = "a.overlay-link"

[rvl]
title = "Rosenberg Van Leusden makelaars"
url = "https://www.rvlmakelaars.nl/koopwoningen-utrecht?e=401000"
entrySelector = ".h-card"
titleSelector = ".p-name"
linkSelector = "a.home"

[molenbeek]
title = "Molenbeek makelaars"
url = "https://molenbeek.nl/wonen/aanbod?buyOrRent=buy&maxPrice=400000&amountOfRooms=3&textSearch=Utrecht&orderBy=created_at&orderDirection=desc"
entrySelector = ".grid-objects__item"
titleSelector = ".card--default__body"
linkSelector = "a.card--object"

[brecheisen]
title = "Brecheisen makelaars"
url = "https://www.brecheisen.nl/woningaanbod/koop/utrecht?iscustom=true&isnewstate=false&locationofinterest=Utrecht&minrooms=3&moveunavailablelistingstothebottom=true&orderby=7&pricerange.maxprice=400000"
entrySelector = ".objectcontainer"
titleSelector = ".obj_address"
linkSelector = "a.sys-property-link"

[punt]
title = "Punt Makelaars"
url = "https://puntmakelaars.nl/nl/aanbod/woningen/?q=&typeBouw=appartement&typeBouw=woning&typeWoning=tussenwoning&typeWoning=portiekflat&typeWoning=bovenwoning&typeWoning=benedenwoning&typeWoning=hoekwoning&typeWoning=galerijflat&typeWoning=portiekwoning&typeWoning=eindwoning&typeWoning=maisonnette&typeWoning=vrijstaande+woning&typeWoning=2-onder-1-kapwoning&typeWoning=halfvrijstaande+woning&typeWoning=geschakelde+2-onder-1-kapwoning&typeWoning=penthouse&typeWoning=beneden+%2B+bovenwoning&typeWoning=geschakelde+woning&typeWoning=tussenverdieping&typeWoning=verspringend&prijs=0-20000&prijs=20000-40000&prijs=40000-60000&prijs=60000-80000&prijs=80000-100000&prijs=100000-125000&prijs=125000-150000&prijs=150000-175000&prijs=175000-200000&prijs=200000-250000&prijs=250000-300000&prijs=300000-350000&prijs=350000-400000"
entrySelector = "ul.listHouses li"
titleSelector = ".houseOverviewPopup"
linkSelector = "a"
filters = ["Kantoor", "Schrijf je nu in", "Verkocht"]

[ingridvaneck]
title = "Ingrid van Eck Makelardij"
url = "https://www.ingridvaneck.nl/te-koop/"
entrySelector = ".col-md-3"
titleSelector = ".card__body"
linkSelector = "a"
filters = ["Verkocht"]

[kraaijkamp]
title = "Kraaijkamp Makelaars"
url = [
	"https://www.kraaijkampmakelaars.nl/object_overview.php?f_show=list&f_sate=norm&f_type=&f_sort=price&f_ordr=DESC&f_pnum=1&f_pmin=&f_pmax=400000&f_smin=&f_smax=&f_city=Utrecht&f_dist=5000",
	"https://www.kraaijkampmakelaars.nl/object_overview.php?f_show=list&f_sate=norm&f_type=&f_sort=price&f_ordr=DESC&f_pnum=2&f_pmin=&f_pmax=400000&f_smin=&f_smax=&f_city=Utrecht&f_dist=5000"
]
entrySelector = "article.object"
titleSelector = ".details"
linkSelector = "a.link_invis"
filters = ["sold"]

[gustocasa]
title = "Gusto Casa"
url = "https://www.gustocasa.nl/woningen/?status=beschikbaar&type=&prijsvan=&prijstot=450000&orderby=status%3Aasc"
entrySelector = ".woning"
titleSelector = ".item-content-inner"
linkSelector = "a.thumbnail"
filters = ["EINDHOVEN"]

[walton]
title = "Walton Makelaars"
url = "https://www.walton.nl/nieuw-in-verkoop-makelaar"
entrySelector = ".object"
titleSelector = "h4"
linkSelector = "a.adreslink"
filters = ["Onder bod", "Verkocht"]

[huf]
title = "Makelaardij Huf"
url = "https://www.makelaardijhuf.nl/aanbod"
entrySelector = ".object"
titleSelector = "h4"
linkSelector = "a.adreslink"
filters = ["Onder bod", "Verkocht", "Zeist", "Meern", "Hilversum"]

[blauweeik]
title = "Blauwe Eik makelaardij"
url = "https://www.blauweeik.nl/wonen/zoeken/Utrecht/5km/0-400000/koop/"
entrySelector = "offer__result li"
titleSelector = "article"
linkSelector = "figure a"
filters = ["Onder bod", "Verkocht", "V.O.V.", "Wil jij liever persoonlijk advies?"]

#[mijnhuisverkoopikzelf]
#title = "Mijn huis verkoop ik zelf"
#url = "https://www.mijnhuisverkoopikzelf.nl/aanbod/koop/stad/utrecht"
#entrySelector = ".card"
#titleSelector = ".card-section"
## They only have a data-url attribute :(
#linkSelector = "a"
#filters = ["Onder bod", "Verkocht", "V.O.V.", "Wil jij liever persoonlijk advies?"]

[wd]
title = "WD Makelaars"
url = "https://wdmakelaars.nl/woningen/"
entrySelector = ".card"
titleSelector = ".card-body"
linkSelector = "a"

[dekeizer]
title = "De Keizer makelaarsgroep"
url = "https://www.dekeizer.nl/woningaanbod/koop/utrecht/type-appartement,woonhuis?iscustom=true&isnewstate=false&locationofinterest=Utrecht&minrooms=3&orderby=9&pricerange.maxprice=400000"
entrySelector = ".objectcontainer"
titleSelector = ".object_data"
linkSelector = "a.sys-property-link"

[lef]
title = "LEF Makelaars"
url = "https://www.lefmakelaars.nl/actueel-aanbod/?fwp_locaties=utrecht&fwp_koopprijs=172500.00%2C400410.00"
entrySelector = ".aanbod"
titleSelector = ".row"
linkSelector = "a.aanbod-item"

[makelaarsland]
title = "Makelaarsland"
url = "https://www.makelaarsland.nl/huis-kopen/?_q=Utrecht&min=&max=400000&type=&kamers=3"
entrySelector = ".m-search-result"
titleSelector = ".m-search-result__content-wrap"
linkSelector = ".m-search-result__content-wrap"

[coversjonker]
title = "Covers & Jonker Makelaars"
url = "https://coversjonker.nl/aanbod/koop?price_buy=0_500"
entrySelector = ".thumbs-item"
titleSelector = "h3"
linkSelector = ".slick-slide a"
filters = ["Onder bod", "Verkocht", "VERKOCHT", "Amsterdam", "Nieuwegein", "Zeist", "De Bilt", "Bilthoven", "Bosch en Duin"]

[lauteslager]
title = "Lauteslager Makelaar"
url = "https://www.lauteslager.nl/nl/aanbod?type=koop&plaats=utrecht&s=&prijs_test%5Bmin%5D=&prijs_test%5Bmax%5D=400000&aantalKamers%5B%5D=3&aantalKamers%5B%5D=&woonoppervlakte%5B%5D=65msup2sup&woonoppervlakte%5B%5D="
entrySelector = ".offer-list-item"
titleSelector = ".item-data h1"
linkSelector = "a.primary-btn"
waitUntil = "networkidle"

[vanscherpenzeel]
title = "Van Scherpenzeel Makelaars"
url = "https://vanscherpenzeel.nl/woningen/makelaar/935799"
entrySelector = "#entity-items .woning"
titleSelector = "h2 a:last-child"
linkSelector = "h2 a.overlay"
matchAllOf = ["Utrecht", "Beschikbaar"]
waitUntil = "networkidle"

[gevaert]
title = "Gevaert-makelaar"
url = "https://www.gevaertmakelaars.nl/koop?city%5B%5D=UTRECHT&sale_price_from=&sale_price_until=400000&surface_lot_from=&surface_living_from="
entrySelector = ".object-block"
titleSelector = ".objectblock__body-address"
linkSelector = "a.objectblock"
matchAllOf = ["BESCHIKBAAR"]

[janwolters]
title = "Jan Wolters Makelaardij"
url = "https://www.janwoltersmakelaardij.nl/woningaanbod/koop/utrecht?locationofinterest=Utrecht&minlivablearea=75&minrooms=3&moveunavailablelistingstothebottom=true&orderby=3&pricerange.maxprice=400000"
entrySelector = ".objectcontainer"
titleSelector = ".obj_address"
linkSelector = ".obj_address a"

[vanvulpenroozenburg]
title = "Van Vulpen & Roozenburg makelaars"
url = "https://www.vanvulpenroozenburg.nl/aanbod/?filter-group-id=3&filter[11]=&filter[14][]=UTRECHT&filter[12]=&range-filter-to=400000&filter[15]=%2C400000"
entrySelector = ".object-block"
titleSelector = ".object-content-header"
linkSelector = "a"

[mommersteeg]
title = "Mommersteeg Makelaardij"
url = "https://www.mommersteegmakelaardij.nl/woning/"
entrySelector = ".woning"
titleSelector = ".objectTitle"
linkSelector = "a.objectTitle"
matchAllOf = ["Utrecht", "Beschikbaar"]

[welzenes]
title = "Van Welzenes Makelaars"
url = "https://www.vanwelzenes.nl/aanbod/"
entrySelector = "[data-filter-price='250001-500000'][data-filter-place='utrecht']"
titleSelector = "h3"
linkSelector = "a"

[beumer]
title = "Beumer Utrecht"
url = "https://beumerutrecht.nl/woningen/"
entrySelector = ".card--wonen"
titleSelector = "h3"
linkSelector = "a.card__overlay"
matchAllOf = ["Utrecht", "Beschikbaar"]

[deruiter]
title = "De Ruiter Makelaarshuis"
url = "https://www.deruitermakelaarshuis.nl/utrecht/woningen/"
entrySelector = ".woning"
titleSelector = "li:first-child dl dd"
linkSelector = "a.thumbnail"
matchAllOf = ["Utrecht", "nieuwsticker"]

[wij]
title = "Wij Makelaardij"
url = "https://www.wijmakelaardij.nl/woningaanbod/"
entrySelector = ".item-woning"
titleSelector = ".title .left p"
linkSelector = "a.overlay"
matchAllOf = ["Utrecht", "Beschikbaar", "k.k."]
waitUntil = "networkidle"

[dekoning]
title = "De Koning Wonen"
url = "https://www.dekoningwonen.nl/woningaanbod/prijs-tot+400000/page+1/plaats+Utrecht/status+tekoop/aanbodtype+koop/aantal-slaapkamers+2"
entrySelector = ".rw-wonen-teaser"
titleSelector = ".rw-wonen-teaser__anchor"
linkSelector = ".rw-wonen-teaser__anchor"
matchAllOf = ["Utrecht", "nieuw"]

[starthousing]
title = "StartHousing"
url = "https://www.starthousing.nl/woningaanbod/koop/utrecht?locationofinterest=Utrecht&minrooms=3&moveunavailablelistingstothebottom=true&pricerange.maxprice=400000"
entrySelector = ".new_forsale"
titleSelector = "h2"
linkSelector = "a.sys-property-link"
matchAllOf = ["Utrecht", "Nieuw"]
waitUntil = "networkidle"

[ludenhoff]
title = "Ludenhoff Groep"
url = "https://www.ludenhoff.nl/aanbod-utrecht"
entrySelector = ".object"
titleSelector = ".adres"
linkSelector = "a.adreslink"
matchAllOf = ["UTRECHT", "€ 3"]
waitUntil = "networkidle"

[waltmann]
title = "Waltmann Makelaars"
url = "https://www.waltmann.nl/wonen/zoeken/heel-nederland/utrecht/0-400000/koop/3-kamers/beschikbaar/"
entrySelector = ".card-house"
titleSelector = "h4"
linkSelector = "*"

[aspektmakelaars]
title = "Aspekt Makelaars"
url = "https://www.aspektmakelaars.nl/wonen/zoeken/heel-nederland/utrecht/0-400000/koop/3-kamers/beschikbaar/"
entrySelector = ".card-house"
titleSelector = "h4"
linkSelector = "*"

[domstadmakelaars]
title = "Domstad Makelaars"
url = "https://domstadmakelaars.nl/woningen/"
entrySelector = ".woning"
titleSelector = "h2"
linkSelector = "a.thumbnail"
matchAllOf = ["Utrecht", "€ 3"]
