[default]
timeout = 300
filters = ["Onder bod", "verkocht", "Verkocht", "VERKOCHT", "dreef", "EINDHOVEN"]
onFail = "stale"
waitUntil = "load"

[peekenpompe]
title = "Peek & Pompe makelaars"
url = "https://www.peekenpompe.nl/nl/woningaanbod?ignoreType[]=isBought#{%22view%22:%22grid%22,%22sort%22:%22addedDesc%22,%22address%22:%22%22,%22title%22:%22%22,%22salesRentals%22:%22sales%22,%22salesPriceMin%22:0,%22salesPriceMax%22:700000,%22devSalesPriceMin%22:0,%22devSalesPriceMax%22:9999999999,%22rentalsPriceMin%22:0,%22rentalsPriceMax%22:9999999999,%22devRentalsPriceMin%22:0,%22devRentalsPriceMax%22:9999999999,%22surfaceMin%22:0,%22surfaceMax%22:9999999999,%22unitsMin%22:0,%22unitsMax%22:9999999999,%22devSurfaceMin%22:0,%22devSurfaceMax%22:9999999999,%22plotSurfaceMin%22:0,%22plotSurfaceMax%22:9999999999,%22roomsMin%22:4,%22roomsMax%22:9999999999,%22bedroomsMin%22:0,%22bedroomsMax%22:9999999999,%22bathroomsMin%22:0,%22bathroomsMax%22:9999999999,%22city%22:[%22Utrecht%22],%22district%22:[],%22mainType%22:[],%22buildType%22:[],%22tag%22:[],%22country%22:[],%22state%22:[],%22listingsType%22:[],%22ignoreType%22:[%22isBought%22],%22categories%22:[],%22status%22:%22available%22,%22statusStrict%22:false,%22user%22:%22%22,%22branch%22:%22%22,%22archiveTime%22:0,%22page%22:1}"
entrySelector = ".card-object"
titleSelector = ".card-object-address"
linkSelector = ".card-object-address"
waitUntil = "domcontentloaded"

# [moib]
# title = "MOIB makelaars"
# url = "https://moib.nl/aanbod/"
# entrySelector = ".horizon"
# titleSelector = "h3"
# linkSelector = "a.overlay-link"
# waitUntil = "domcontentloaded"

# [rvl]
# title = "Rosenberg Van Leusden makelaars"
# url = "https://www.rvlmakelaars.nl/koopwoningen-utrecht?a=Utrecht&e=700000"
# entrySelector = ".h-card"
# titleSelector = ".p-name"
# linkSelector = "a.home"

[molenbeek]
title = "Molenbeek makelaars"
url = "https://molenbeek.nl/wonen/aanbod?buy_rent=buy&buy_price=-700000&rooms_amount=4-6&status=beschikbaar&total_living_surface=100-&order_by=created_at-desc&page=1"
entrySelector = ".grid-objects__item"
titleSelector = ".card--default__body"
linkSelector = "a.card--object"
waitUntil = "domcontentloaded"

[brecheisen]
title = "Brecheisen makelaars"
url = "https://www.brecheisen.nl/woningen/aanbod/zoeken/Utrecht+/beschikbaar/koop/0-650000/3-kamers"
entrySelector = ".card-house"
titleSelector = "h3"
linkSelector = "a"
waitUntil = "networkidle"

# [punt]
# title = "Punt Makelaars"
# url = "https://puntmakelaars.nl/alle-woningen/?search=Utrecht&filter-price-max=700000&filter-livingArea=100&filter-rooms=3&filter-status=BESCHIKBAAR&filter-number-rooms-order=0"
# entrySelector = "ul.housing-offer__list li"
# titleSelector = "h2"
# linkSelector = "a"

[ingridvaneck]
title = "Ingrid van Eck Makelardij"
url = "https://www.ingridvaneck.nl/te-koop/"
entrySelector = ".col-md-3"
titleSelector = ".card__body"
linkSelector = "a"
matchAllOf = ["Utrecht", "€5"]
waitUntil = "load"

# [kraaijkamp]
# title = "Kraaijkamp Makelaars"
# url = "https://kraaijkampmakelaars.nl/nl/koop/woning-aanbod/"
# entrySelector = "article.object"
# titleSelector = ".details"
# linkSelector = "a.link_invis"
# filters = ["sold"]
# waitUntil = "domcontentloaded"

# [gustocasa]
# title = "Gusto Casa"
# url = "https://www.gustocasa.nl/woningen/?status=beschikbaar&type=&prijsvan=&prijstot=450000&orderby=status%3Aasc"
# entrySelector = ".woning"
# titleSelector = ".item-content-inner"
# linkSelector = "a.thumbnail"
# waitUntil = "domcontentloaded"

[walton]
title = "Walton Makelaars"
url = "https://www.walton.nl/aanbod-makelaar/?_plaatsen=utrecht&_prijs_van=500000-9999999&_prijs_tot=1-700000"
entrySelector = ".object"
titleSelector = ".object-address-line"
linkSelector = "a.d-table"
matchAllOf = ["Nieuw"]
waitUntil = "networkidle"

[huf]
title = "Makelaardij Huf"
url = "https://www.makelaardijhuf.nl/aanbod/?_plaatsen=utrecht&_prijs_van=500000-9999999&_prijs_tot=1-700000"
entrySelector = ".object"
titleSelector = "h4"
linkSelector = "a.adreslink"
filters = ["Onder bod", "Verkocht", "Zeist", "Meern", "Hilversum"]
waitUntil = "domcontentloaded"

[blauweeik]
title = "Blauwe Eik makelaardij"
url = "https://www.blauweeik.nl/wonen/zoeken/Utrecht/5km/0-700000/100-oppervlakte/koop/"
entrySelector = ".offer__result li"
titleSelector = "h4"
linkSelector = "figure a"
filters = ["Onder bod", "Verkocht", "V.O.V.", "Wil jij liever persoonlijk advies?"]
waitUntil = "networkidle"

#[mijnhuisverkoopikzelf]
#title = "Mijn huis verkoop ik zelf"
#url = "https://www.mijnhuisverkoopikzelf.nl/aanbod/koop/stad/utrecht"
#entrySelector = ".card"
#titleSelector = ".card-section"
## They only have a data-url attribute :(
#linkSelector = "a"
#filters = ["Onder bod", "Verkocht", "V.O.V.", "Wil jij liever persoonlijk advies?"]

# [wd]
# title = "WD Makelaars"
# url = "https://wdmakelaars.nl/woningen/"
# entrySelector = ".card"
# titleSelector = ".card-body"
# linkSelector = "a"
# waitUntil = "domcontentloaded"

# [dekeizer]
# title = "De Keizer makelaarsgroep"
# url = "https://www.dekeizer.nl/woningaanbod/koop/utrecht/type-appartement,woonhuis?iscustom=true&isnewstate=false&locationofinterest=Utrecht&minrooms=3&orderby=9&pricerange.maxprice=400000"
# entrySelector = ".objectcontainer"
# titleSelector = ".object_data"
# linkSelector = "a.sys-property-link"
# waitUntil = "domcontentloaded"

[lef]
title = "LEF Makelaars"
url = "https://www.lefmakelaars.nl/actueel-aanbod/?fwp_locaties=utrecht&fwp_status=te-koop&fwp_koopprijs=172500.00%2C699440.00&fwp_oppervlakte=98.00%2C165.00"
entrySelector = ".aanbod"
titleSelector = ".row"
linkSelector = "a.aanbod-item"

[makelaarsland]
title = "Makelaarsland"
url = "https://www.makelaarsland.nl/huis-kopen/?_q=Utrecht&min=&max=700000&type=&kamers=4"
entrySelector = ".m-search-result"
titleSelector = ".m-search-result__content-wrap"
linkSelector = ".m-search-result__content-wrap"
waitUntil = "domcontentloaded"

# [coversjonker]
# title = "Covers & Jonker Makelaars"
# url = "https://coversjonker.nl/aanbod/koop?price_buy=0_500"
# entrySelector = ".thumbs-item"
# titleSelector = "h3"
# linkSelector = ".slick-slide a"
# filters = ["Onder bod", "Verkocht", "VERKOCHT", "Amsterdam", "Nieuwegein", "Zeist", "De Bilt", "Bilthoven", "Bosch en Duin"]

[lauteslager]
title = "Lauteslager Makelaar"
url = "https://www.lauteslager.nl/nl/aanbod?type=koop&plaats=utrecht&s=&prijs_test%5Bmin%5D=&prijs_test%5Bmax%5D=700000&aantalKamers%5B%5D=4&aantalKamers%5B%5D=5&aantalKamers%5B%5D=6&aantalKamers%5B%5D=&woonoppervlakte%5B%5D=70msup2sup&woonoppervlakte%5B%5D=72msup2sup&woonoppervlakte%5B%5D=73msup2sup&woonoppervlakte%5B%5D="
entrySelector = ".offer-list-item"
titleSelector = ".item-data h1"
linkSelector = "a.primary-btn"
waitUntil = "networkidle"

# [vanscherpenzeel]
# title = "Van Scherpenzeel Makelaars"
# url = "https://vanscherpenzeel.nl/woningen/makelaar/935799"
# entrySelector = "#entity-items .woning"
# titleSelector = "h2 a:last-child"
# linkSelector = "h2 a.overlay"
# matchAllOf = ["Utrecht", "Beschikbaar", "€ 3"]
# waitUntil = "networkidle"

[gevaert]
title = "Gevaert-makelaar"
url = "https://www.gevaertmakelaars.nl/koop?city%5B%5D=UTRECHT&sale_price_from=&sale_price_until=700000&surface_lot_from=&surface_living_from=100"
entrySelector = ".object-block"
titleSelector = ".objectblock__body-address"
linkSelector = "a.objectblock"
matchAllOf = ["BESCHIKBAAR"]
waitUntil = "domcontentloaded"

[janwolters]
title = "Jan Wolters Makelaardij"
url = "https://www.janwoltersmakelaardij.nl/woningaanbod/koop/utrecht?locationofinterest=Utrecht&minlivablearea=100&minrooms=4&moveunavailablelistingstothebottom=true&orderby=3&pricerange.maxprice=700000"
entrySelector = ".objectcontainer"
titleSelector = ".obj_address"
linkSelector = ".obj_address a"

[vanvulpenroozenburg]
title = "Van Vulpen & Roozenburg makelaars"
url = "https://www.vanvulpenroozenburg.nl/aanbod/?filter-group-id=3&filter[11]=&filter[14][]=UTRECHT&filter[12]=&range-filter-to=700000&filter[15]=%2C700000"
entrySelector = ".object-block"
titleSelector = ".object-content-header"
linkSelector = "a"

[mommersteeg]
title = "Mommersteeg Makelaardij"
url = "https://www.mommersteegmakelaardij.nl/woning/"
entrySelector = ".woning"
titleSelector = ".objectTitle"
linkSelector = "a.objectTitle"
matchAllOf = ["Utrecht", "Beschikbaar", "€ 5"]
waitUntil = "domcontentloaded"

# [welzenes]
# title = "Van Welzenes Makelaars"
# url = "https://www.vanwelzenes.nl/aanbod/"
# entrySelector = "[data-filter-price='250001-500000'][data-filter-place='utrecht']"
# titleSelector = "h3"
# linkSelector = "a"
# waitUntil = "domcontentloaded"

[beumer]
title = "Beumer Utrecht"
url = "https://www.beumer.nl/wonen/zoeken/heel-nederland/0-700000/utrecht/100-oppervlakte/3-slaapkamers/beschikbaar/"
entrySelector = ".section--houses .house-col"
titleSelector = "h3"
linkSelector = "a.card-house"

[deruiter]
title = "De Ruiter Makelaarshuis"
url = "https://www.deruitermakelaarshuis.nl/aanbod/?_status=te-koop&_locaties=utrecht&_koopprijs=%2C700000&_oppervlakte=100-200"
entrySelector = ".aanbod-item"
titleSelector = "h5"
linkSelector = "*"

[wij]
title = "Wij Makelaardij"
url = "https://www.wijmakelaardij.nl/woningaanbod/"
entrySelector = ".item-woning"
titleSelector = ".title .left p"
linkSelector = "a.overlay"
matchAllOf = ["Utrecht", "Beschikbaar", "k.k.", "€ 5"]
waitUntil = "networkidle"

[dekoning]
title = "De Koning Wonen"
url = "https://www.dekoningwonen.nl/woningaanbod/prijs-tot+400000/page+1/plaats+Utrecht/status+tekoop/aanbodtype+koop/aantal-slaapkamers+3/woonoppervlakte+200"
entrySelector = ".rw-wonen-teaser"
titleSelector = ".rw-wonen-teaser__anchor"
linkSelector = ".rw-wonen-teaser__anchor"
matchAllOf = ["Utrecht", "nieuw"]
waitUntil = "domcontentloaded"

[365makelaardij]
title = "365makelaardij"
url = "https://365makelaardij.nl/wonen/zoeken/heel-nederland/koop/utrecht/3-slaapkamers/beschikbaar/"
entrySelector = ".house-list__item"
titleSelector = "h4"
linkSelector = "a.card-property"
waitUntil = "networkidle"

[ludenhoff]
title = "Ludenhoff Groep"
url = "https://www.ludenhoff.nl/wonen/zoeken/heel-nederland/utrecht/4-kamers/beschikbaar/"
entrySelector = ".card-product"
titleSelector = "h5"
linkSelector = "a.card-product__link"
waitUntil = "networkidle"
matchOneOf = ["€ 5", "€ 6"]

[waltmann]
title = "Waltmann Makelaars"
url = "https://www.waltmann.nl/wonen/zoeken/heel-nederland/0-650000/koop/utrecht/3-kamers/beschikbaar/"
entrySelector = ".card-house"
titleSelector = "h4"
linkSelector = "*"
waitUntil = "domcontentloaded"

[aspektmakelaars]
title = "Aspekt Makelaars"
url = "https://www.aspektmakelaars.nl/wonen/zoeken/heel-nederland/koop/0-400000/utrecht/4-kamers/3-slaapkamers/beschikbaar/"
entrySelector = ".card-house"
titleSelector = "h2"
linkSelector = "*"

[domstadmakelaars]
title = "Domstad Makelaars"
url = "https://domstadmakelaars.nl/woningen/?adres=&type%5B%5D=koop&type%5B%5D=&prijs%5Bmin%5D=&prijs%5Bmax%5D=699000&plaats%5B%5D=utrecht&plaats%5B%5D=&woningtype%5B%5D="
entrySelector = ".woning"
titleSelector = "h2"
linkSelector = "a.thumbnail"
matchAllOf = ["Utrecht", "4 kamers"]

# [veldhuizenkoot]
# title = "Veldhuizenkoot Makelaars"
# url = "https://veldhuizenkoot.nl/woningen/?type=koop&plaats=utrecht&radius=&adres="
# entrySelector = ".houseblock"
# titleSelector = ".adres"
# linkSelector = "a.check"
# matchAllOf = ["€ 5"]
# waitUntil = "domcontentloaded"

[jipmakelaars]
title = "JIP Makelaars"
url = "https://jipmakelaars.nl/woningen/?s=Utrecht&area=0&vanField=&totField=700000&van=&tot=700000&soort_object=Woningsoort&slaapkamers=3&woonoppervlakte=Woonoppervlakte&aangebodensinds=Aangeboden+sinds&object_type=1"
entrySelector = ".property"
titleSelector = ".property-block .row:nth-child(2)"
linkSelector = "a"
waitUntil = "networkidle"

[broekmancalis]
title = "Broekman & Calis Makelaars"
url = "https://www.broekman-calis.nl/aanbod"
entrySelector = ".object-info"
titleSelector = ".adres"
linkSelector = "a.adreslink"
matchAllOf = ["€ 5", "Utrecht"]

[thijssenmakelaars]
title = "Paul Thijssen makelaars"
url = "https://thijssenmakelaars.nl/woningen/?plaats=utrecht&price_min=219000&price_max=620000&aantal_kamers=3&m2_min=75&m2_max=303"
entrySelector = "#dm-wonen-listing-grid .grid>.relative.w-full"
titleSelector = "h3"
linkSelector = "a"

[stapmakelaars]
title = "Stap makelaars"
url = "https://www.stapmakelaars.nl/woningaanbod/#HYtLDoAgDETv0jULN8bE2xRCAoKWlKImhLtbnNX8XodEVEJrDPtvwUDJiFI1N2Hvgmg1l8Lx0LbDia-O2zIFw0AVlDb_1lcXYrKIrMxDdCnl-c6YxE9khfEB"
entrySelector = "#entity-items article.card"
titleSelector = "h3"
linkSelector = "a"

[overduyn]
title = "overduyn makelaars"
url = "https://overduyn.nl/koopaanbod/?_prijs_tot=1-650000&_plaatsen=utrecht&_slaapkamers=3-100"
entrySelector = ".facetwp-template>.col-12"
titleSelector = ".object-address-line"
linkSelector = "a"

[vandenhoornmakelaardij]
title = "van den Hoorn Makelaardij"
url = "https://www.vandenhoornmakelaardij.nl/woningaanbod/koop/utrecht?availability=1&locationofinterest=Utrecht&minrooms=3&pricerange.maxprice=650000"
entrySelector = ".object_container"
titleSelector = "h2"
linkSelector = "a"

[yourhouse]
title = "Your House"
url = "https://your-house.nl/woningaanbod/koop/utrecht?availability=1&iscustom=true&locationofinterest=Utrecht&minrooms=3&moveunavailablelistingstothebottom=true&orderby=10&orderdescending=true&pricerange.maxprice=650000"
entrySelector = ".object_container"
titleSelector = "h2"
linkSelector = "a"

[mozaiekmakelaardij]
title = "Mozaiek Makelaardij"
url = "https://www.mozaiekmakelaardij.nl/woningaanbod"
entrySelector = ".object__holder"
titleSelector = "h3 .street"
linkSelector = "a"
matchAllOf = ["€ 5", "Utrecht", "Woonhuis", "Nieuw in verkoop"]

[markrenkemamakelaardij]
title = "Mark Renkema Makelaardij"
url = "https://www.markrenkemamakelaardij.nl/wonen/zoeken/Utrecht/0-650000/"
entrySelector = ".houses__item"
titleSelector = ".card-product__content p"
linkSelector = "a"
matchAllOf = ["€ 5", "Beschikbaar", "Utrecht"]

[morgenmakelaardij]
title = "Morgen Makelaardij"
url = "https://www.morgenmakelaardij.nl/nl/woningaanbod/koop?salesRentals=sales#{%22view%22:%22grid%22,%22sort%22:%22addedDesc%22,%22address%22:%22%22,%22title%22:%22%22,%22salesRentals%22:%22sales%22,%22salesPriceMin%22:0,%22salesPriceMax%22:650000,%22devSalesPriceMin%22:0,%22devSalesPriceMax%22:9999999999,%22rentalsPriceMin%22:0,%22rentalsPriceMax%22:9999999999,%22devRentalsPriceMin%22:0,%22devRentalsPriceMax%22:9999999999,%22surfaceMin%22:0,%22surfaceMax%22:9999999999,%22unitsMin%22:0,%22unitsMax%22:9999999999,%22devSurfaceMin%22:0,%22devSurfaceMax%22:9999999999,%22plotSurfaceMin%22:0,%22plotSurfaceMax%22:9999999999,%22roomsMin%22:3,%22roomsMax%22:9999999999,%22bedroomsMin%22:0,%22bedroomsMax%22:9999999999,%22bathroomsMin%22:0,%22bathroomsMax%22:9999999999,%22city%22:[],%22district%22:[],%22mainType%22:[],%22buildType%22:[],%22tag%22:[],%22country%22:[],%22state%22:[],%22listingsType%22:[],%22ignoreType%22:[],%22categories%22:[],%22status%22:%22available%22,%22statusStrict%22:true,%22user%22:%22%22,%22branch%22:%22%22,%22archiveTime%22:15778463,%22page%22:1}"
entrySelector = ".card-object"
titleSelector = ".card-object-address"
linkSelector = "a"
matchAllOf = ["€ 5", "Utrecht"]

[huisportaal]
title = "Huisportaal"
url = "https://huisportaal.nl/koopwoningen"
entrySelector = ".property"
titleSelector = ".address"
linkSelector = "a"
matchAllOf = ["€ 5", "Utrecht"]

[burgersdijk]
title = "Burgersdijk makelaars"
url = "https://burgersdijk.com/koopwoningen/?in=utrecht&tot=600000"
entrySelector = "a[data-openday]"
titleSelector = "h3"
linkSelector = "*"
filters = ["Aantal kamers 1", "Aantal kamers 2", "onder bod", "Onder bod", "verkocht", "Verkocht", "VERKOCHT", "dreef", "EINDHOVEN"]

[reineriehouten]
title = "Reinerie Houten"
url = "https://reineriehouten.nl/woningen/#HY3LCgIxDEX_Jesiguii_-FKZOgj0NrptCQpKMP8u-lkleRczt2huoKrcwT2BYR5Q8qY2hDcLtsKbwOltZ7G0MC5goGueeGlN5bQIip4CmFIMhnlD4Pd1ftV8LhfdeAwwOJk8GzxyCHl4mep-lltvbiKpBRu6mgUkfxPrzBYWl3Oh3UcTB9-zcFJxqi6aqO64PgD"
entrySelector = ".card--wonen"
titleSelector = "[itemprop=streetAddress]"
linkSelector = "a"
waitUntil = "networkidle"

[pauwmakelaardij]
title = "Pauw Makelaardij"
url = "https://www.pauwmakelaardij.nl/aanbod/?view=list&straat&plaats=utrecht&prijs_vanaf=0&prijs_tot=650000&buitenruimte%5B0%5D=achtertuin&buitenruimte%5B1%5D=tuin-rondom&buitenruimte%5B2%5D=voortuin&woonoppervlakte=75"
entrySelector = ".rw_makelaar_houses"
titleSelector = "h3"
linkSelector = "a"
filters = ["Slaapkamers: 2", "onder bod", "Onder bod", "verkocht", "Verkocht", "VERKOCHT", "dreef", "EINDHOVEN"]

[domvast]
title = "Domvast"
url = "https://domvast.nl/woningen/#q1YqyElMLClWslIqLSlKTc4oUdJRKi5JLCkFCkUrJaUWJ2dkZiclJhYpxeoo5RelpBYlVQIVQ5RYJRYnK9UCAA"
entrySelector = ".woning"
titleSelector = "header h2:last-child"
linkSelector = "a"
matchAllOf = ["€ 5", "UTRECHT", "Beschikbaar"]

[pauldijkstra]
title = "Paul Dijkstra makelaars"
url = "https://www.leefengeniet.nl/woningen/#FclLDoAgDEXRvbwxAxI_A3dToYkKCKk10Rj3bh3ecx-0TKQHJpwqHBaFA9GulBMVln90RqnW1mTdrB8UuozHfvDe43WoElnm2yyS8hT5CHg_"
entrySelector = ".woning"
titleSelector = ".item-content header h2"
linkSelector = "a.overlay"
# THe `waitUntil` doesn't seem to be sufficient for waiting for the search to be completed:
matchAllOf = ["€ 5", "Utrecht", "Beschikbaar", "Woonhuis"]
waitUntil = "networkidle"

[vandoorn]
title = "Van Doorn makelaardij"
url = "https://www.van-doorn.nl/woningen/#q1YqyElMLClWslIqLSlKTc4oUdJRKijKzAKKVCvlJlYAJcwNQECpthYA"
entrySelector = "#entity-items > .grid"
titleSelector = "h2"
linkSelector = "a"
matchAllOf = ["€ 5", "Utrecht", "Beschikbaar", "Woonhuis"]
waitUntil = "networkidle"

[ddvmakelaars]
title = "DDV makelaars"
url = "https://www.ddvmakelaars.com/aanbod"
entrySelector = ".aanbod-card-wrapper [role=listitem]"
titleSelector = ".aanbod-blog-card-item :nth-child(4) :first-child :first-child"
linkSelector = "a"
matchAllOf = ["€ 5", "Utrecht"]

[coverswonen]
title = "Covers wonen"
url = "https://coverswonen.nl/aanbod/koop"
entrySelector = ".col-sm-6"
titleSelector = "h3"
linkSelector = "a"
matchAllOf = ["€ 5", "Utrecht"]

[dinaverkoopt]
title = "Dina verkoopt"
url = "https://www.dinaverkoopt.nl/woning-aanbod/?view=list&straat&plaats=utrecht&prijs_vanaf=0&prijs_tot=600000&buitenruimte%5B0%5D=achtertuin&buitenruimte%5B1%5D=patio-atrium&buitenruimte%5B2%5D=voortuin&buitenruimte%5B3%5D=zijtuin&buitenruimte%5B4%5D=zonneterras&woonoppervlakte=75"
entrySelector = "#overzicht-grid .grid-houses__col"
titleSelector = "h4"
linkSelector = "a"
filters = ["1 slaapkamers", "2 slaapkamers", "Onder bod", "verkocht", "Verkocht", "VERKOCHT", "dreef", "EINDHOVEN"]
