[default]
timeout = 180
filters = ["Onder bod", "Verkocht"]

[thijssenmakelaars]
title = "Paul Thijssen makelaars - aanbod"
url = "https://www.thijssenmakelaars.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/2+kamers/"
entrySelector = "li.aanbodEntry"
titleSelector = ".addressInfo"
linkSelector = "a.aanbodEntryLink"

[peekenpompe]
title = "https://www.thijssenmakelaars.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/2+kamers/"
url = "https://www.peekenpompe.nl/nl/woningaanbod?ignoreType[]=isBought#{%22view%22:%22grid%22,%22sort%22:%22addedDesc%22,%22address%22:%22%22,%22title%22:%22%22,%22salesRentals%22:%22sales%22,%22salesPriceMin%22:0,%22salesPriceMax%22:400000,%22devSalesPriceMin%22:0,%22devSalesPriceMax%22:9999999999,%22rentalsPriceMin%22:0,%22rentalsPriceMax%22:9999999999,%22devRentalsPriceMin%22:0,%22devRentalsPriceMax%22:9999999999,%22surfaceMin%22:0,%22surfaceMax%22:9999999999,%22unitsMin%22:0,%22unitsMax%22:9999999999,%22devSurfaceMin%22:0,%22devSurfaceMax%22:9999999999,%22plotSurfaceMin%22:0,%22plotSurfaceMax%22:9999999999,%22roomsMin%22:2,%22roomsMax%22:9999999999,%22bedroomsMin%22:0,%22bedroomsMax%22:9999999999,%22bathroomsMin%22:0,%22bathroomsMax%22:9999999999,%22city%22:[%22Utrecht%22],%22district%22:[],%22mainType%22:[],%22buildType%22:[],%22tag%22:[],%22country%22:[],%22state%22:[],%22listingsType%22:[],%22ignoreType%22:[%22isBought%22],%22categories%22:[],%22status%22:%22available%22,%22statusStrict%22:false,%22user%22:%22%22,%22branch%22:%22%22,%22archiveTime%22:15778463,%22page%22:1}"
entrySelector = ".card-object"
titleSelector = ".card-object-address"
linkSelector = ".card-object-address"

[moib]
title = "MOIB makelaars - aanbod"
url = "https://moib.nl/aanbod/"
entrySelector = ".horizon"
titleSelector = "h3"
linkSelector = "a.overlay-link"

[rvl]
title = "Rosenberg Van Leusden makelaars - aanbod"
url = "https://www.rvlmakelaars.nl/koopwoningen-utrecht?e=401000"
entrySelector = ".h-card"
titleSelector = ".p-name"
linkSelector = "a.home"
timeout = 180

[immo030]
title = "IMMO 030 makelaars - aanbod"
url = "https://www.immo-030.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/2+kamers/"
entrySelector = "li.aanbodEntry"
titleSelector = ".addressInfo"
linkSelector = "a.aanbodEntryLink"

[ansdewijn]
title = "Ans de Wijn woningen - aanbod"
url = "https://www.ansdewijnwoningen.nl/aanbod/woningaanbod/beschikbaar/-400000/koop/"
entrySelector = "li.aanbodEntry"
titleSelector = ".addressInfo"
linkSelector = "a.aanbodEntryLink"

[molenbeek]
title = "Molenbeek makelaars - aanbod"
url = "https://molenbeek.nl/wonen/aanbod?buyOrRent=buy&maxPrice=400000&amountOfRooms=3&textSearch=Utrecht&orderBy=created_at&orderDirection=desc"
entrySelector = ".grid-objects__item"
titleSelector = ".card--default__body"
linkSelector = "a.card--object"

[pauldijkstra]
title = "Paul Dijkstra makelaars - aanbod"
url = "https://www.leefengeniet.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/-400000/koop/provincie-Utrecht/"
entrySelector = "li.aanbodEntry"
titleSelector = ".addressInfo"
linkSelector = "a.aanbodEntryLink"

[nu]
title = "NU makelaardij - aanbod"
url = "https://www.nu-makelaardij.nl/aanbod/woningaanbod/UTRECHT/beschikbaar/-400000/koop/provincie-Utrecht/"
entrySelector = "li.aanbodEntry"
titleSelector = ".addressInfo"
linkSelector = "a.aanbodEntryLink"

[brecheisen]
title = "Brecheisen makelaars - aanbod"
url = "https://www.brecheisen.nl/woningaanbod/koop/utrecht?iscustom=true&isnewstate=false&locationofinterest=Utrecht&minrooms=3&moveunavailablelistingstothebottom=true&orderby=7&pricerange.maxprice=400000"
entrySelector = ".objectcontainer"
titleSelector = ".obj_address"
linkSelector = "a.sys-property-link"
timeout = 180

[clemens]
title = "Clemens de Korte makelaardij - aanbod"
url = "https://www.clemensdekorte.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/3+kamers/"
entrySelector = "li.aanbodEntry"
titleSelector = ".addressInfo"
linkSelector = "a.aanbodEntryLink"

[punt]
title = "Punt Makelaars - aanbod"
url = "https://puntmakelaars.nl/nl/aanbod/woningen/?q=&typeBouw=appartement&typeBouw=woning&typeWoning=tussenwoning&typeWoning=portiekflat&typeWoning=bovenwoning&typeWoning=benedenwoning&typeWoning=hoekwoning&typeWoning=galerijflat&typeWoning=portiekwoning&typeWoning=eindwoning&typeWoning=maisonnette&typeWoning=vrijstaande+woning&typeWoning=2-onder-1-kapwoning&typeWoning=halfvrijstaande+woning&typeWoning=geschakelde+2-onder-1-kapwoning&typeWoning=penthouse&typeWoning=beneden+%2B+bovenwoning&typeWoning=geschakelde+woning&typeWoning=tussenverdieping&typeWoning=verspringend&prijs=0-20000&prijs=20000-40000&prijs=40000-60000&prijs=60000-80000&prijs=80000-100000&prijs=100000-125000&prijs=125000-150000&prijs=150000-175000&prijs=175000-200000&prijs=200000-250000&prijs=250000-300000&prijs=300000-350000&prijs=350000-400000"
entrySelector = "ul.listHouses li"
titleSelector = ".houseOverviewPopup"
linkSelector = "a"
filters = ["Kantoor", "Schrijf je nu in", "Verkocht"]

[ingridvaneck]
title = "Ingrid van Eck Makelardij - aanbod"
url = "https://www.ingridvaneck.nl/te-koop/"
entrySelector = ".col-md-3"
titleSelector = ".card__body"
linkSelector = "a"
filters = ["Verkocht"]
timeout = 240

[kraaijkamp]
title = "Kraaijkamp Makelaars - aanbod"
url = [
	"https://www.kraaijkampmakelaars.nl/object_overview.php?f_show=list&f_sate=norm&f_type=&f_sort=price&f_ordr=DESC&f_pnum=1&f_pmin=&f_pmax=400000&f_smin=&f_smax=&f_city=Utrecht&f_dist=5000",
	"https://www.kraaijkampmakelaars.nl/object_overview.php?f_show=list&f_sate=norm&f_type=&f_sort=price&f_ordr=DESC&f_pnum=2&f_pmin=&f_pmax=400000&f_smin=&f_smax=&f_city=Utrecht&f_dist=5000"
]
entrySelector = "article.object"
titleSelector = ".details"
linkSelector = "a.link_invis"
filters = ["sold"]

[gustocasa]
title = "Gusto Casa - aanbod"
url = "https://www.gustocasa.nl/woningen/?status=beschikbaar&type=&prijsvan=&prijstot=450000&orderby=status%3Aasc"
entrySelector = ".woning"
titleSelector = ".item-content-inner"
linkSelector = "a.thumbnail"
filters = ["EINDHOVEN"]

[walton]
title = "Walton Makelaars - aanbod"
url = "https://www.walton.nl/nieuw-in-verkoop-makelaar"
entrySelector = ".object"
titleSelector = "h4"
linkSelector = "a.adreslink"
filters = ["Onder bod", "Verkocht"]

[huf]
title = "Makelaardij Huf - aanbod"
url = "https://www.makelaardijhuf.nl/aanbod"
entrySelector = ".object"
titleSelector = "h4"
linkSelector = "a.adreslink"
filters = ["Onder bod", "Verkocht", "Zeist", "Meern", "Hilversum"]

[nijland]
title = "Nijland Makelaars - aanbod"
url = "https://www.nijland.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/aantal-80/3+kamers/"
entrySelector = "li.aanbodEntry"
titleSelector = ".addressInfo"
linkSelector = "a.aanbodEntryLink"
filters = ["Onder bod", "Verkocht"]

[blauweeik]
title = "Blauwe Eik makelaardij - aanbod"
url = "https://www.blauweeik.nl/wonen/zoeken/Utrecht/5km/0-400000/koop/"
entrySelector = "offer__result li"
titleSelector = "article"
linkSelector = "figure a"
filters = ["Onder bod", "Verkocht", "V.O.V.", "Wil jij liever persoonlijk advies?"]

#[mijnhuisverkoopikzelf]
#title = "Mijn huis verkoop ik zelf - aanbod"
#url = "https://www.mijnhuisverkoopikzelf.nl/aanbod/koop/stad/utrecht"
#entrySelector = ".card"
#titleSelector = ".card-section"
## They only have a data-url attribute :(
#linkSelector = "a"
#filters = ["Onder bod", "Verkocht", "V.O.V.", "Wil jij liever persoonlijk advies?"]

[wd]
title = "WD Makelaars - aanbod"
url = "https://wdmakelaars.nl/woningen/"
entrySelector = ".card"
titleSelector = ".card-body"
linkSelector = "a"

[leuk]
title = "leuk! makelaars - aanbod"
url = "https://www.leuk-makelaars.nl/aanbod/woningaanbod/UTRECHT/-400000/koop/provincie-Utrecht/"
entrySelector = "li.aanbodEntry"
titleSelector = ".addressInfo"
linkSelector = "a.aanbodEntryLink"
